services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: exercises
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - application-network

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mysql
    environment:
      - MYSQL_URL=jdbc:mysql://mysql:3306/exercises?allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - JWT_SECRET=fake-secret-key
      - SMTP_HOST=fake-smtp-server.com
      - SMTP_PORT=587
      - SMTP_USERNAME=fake_smtp_user
      - SMTP_PASSWORD=fake_smtp_password
      - SMTP_FROM_EMAIL=fake_email@example.com
      - RESET_PASSWORD_BASE_ENDPOINT=http://localhost:5173/password-reset
      - ADMIN_USERNAME=fake_admin
      - ADMIN_EMAIL=fake_admin@mail.com
      - ADMIN_PASSWORD=fake_admin_password
    ports:
      - "8080:8080"
    networks:
      - application-network

volumes:
  mysql_data:

networks:
  application-network:
    driver: bridge